sudo: required

script:
  - ls
  - cp -r front/. .
  - cp -r back/. .
  - rm -rf front
  - rm -rf back
  - sed -i "s,DJANGO_DB_NAME=,DJANGO_DB_NAME=$DJANGO_DB_NAME,g" FakeHub/.env
  - sed -i "s,DJANGO_DB_PASSWORD=,DJANGO_DB_PASSWORD=$DJANGO_DB_PASSWORD,g" FakeHub/.env
  - sed -i "s,DJANGO_DB_USER=,DJANGO_DB_USER=$DJANGO_DB_USER,g" FakeHub/.env
  - sed -i "s,DJANGO_DB_HOST=,DJANGO_DB_HOST=$DJANGO_DB_HOST,g" FakeHub/.env
  - sed -i "s,http://localhost:8000,https://fake-hub.herokuapp.com,g" package.json
  - sed -i "s,http://django:8000,https://fake-hub.herokuapp.com,g" package.json
  - cat FakeHub/.env
  - cat package.json
  - ls
  - git add .
  - git commit -m "Sensei made one good commit for deploy"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: fake-hub
  on: dev
  
#add tests
#add push to docker hub
#add deploy
  
#after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#  - docker push $DOCKER_USERNAME/fake-hub:latest