sudo: required

script:
  - ls
  - cp -f deploy/FakeHub/urls.py back/FakeHub/urls.py
  - cp -f deploy/FakeHub/settings.py back/FakeHub/settings.py
  - cp -r front/. .
  - cp -r back/. .
  - rm -rf front
  - rm -rf back
  - rm -rf deploy
  - sed -i "s,PROXY,https://fake-hub.herokuapp.com,g" package.json
  - cat FakeHub/urls.py
  - ls
  - git add .
  - git commit -m "Prepred for deploy"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: fake-hub
  on: feature/docker-travis-heroku
  
#add tests
#add push to docker hub
#add deploy
  
#after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#  - docker push $DOCKER_USERNAME/fake-hub:latest