sudo: required
language: python
python:
  - '3.9'

# services:
#   - docker

script:
  - mkdir deploy
  - cp /front/. /deploy
  - cp /back/. /deploy
  - rmdir front
  - rmdir back
  - cd deploy
  - sed -i "s,PROXY,https://fake-hub.herokuapp.com,g" package.json
  - cat package.json
  - ls
  
#add tests
#add push to docker hub
#add deploy
  
#after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#  - docker push $DOCKER_USERNAME/fake-hub:latest