sudo: required
language: python
python:
  - '3.9'

# services:
#   - docker

script:
  - ls
  - cp -r front/. .
  - cp -r back/. .
  - rm -rf front
  - rm -rf back
  - rm -rf deploy
  - sed -i "s,PROXY,https://fake-hub.herokuapp.com,g" package.json
  - cat package.json
  - ls

deploy:
  provider: heroku
  api_key: $API_KEY
  app: fake-hub
  on:
    all_branches: true
  
#add tests
#add push to docker hub
#add deploy
  
#after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#  - docker push $DOCKER_USERNAME/fake-hub:latest