sudo: required

script:
  - echo $API_KEY
  - ls
  - cp -r front/. .
  - cp -r back/. .
  - rm -rf front
  - rm -rf back
  - sed -i "s,http://localhost:8000,https://fake-hub.herokuapp.com,g" package.json
  - sed -i "s,http://django:8000,https://fake-hub.herokuapp.com,g" package.json
  - cat package.json
  - ls
  - git add .
  - git commit -m "Sensei made one good commit for deploy"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: fake-hub
  on: feature/docker-travis-heroku
  
#add tests
#add push to docker hub
#add deploy
  
#after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#  - docker push $DOCKER_USERNAME/fake-hub:latest