version: '3.7'

services:
  db:
    image: postgres
    hostname: postgres
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fake-hub
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    container_name: postgres_db
    
  django:
    build: ./back
    restart: on-failure
    environment:
      WAIT_HOSTS: postgres:5432
    volumes:
      - ./back:/app/back
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: django_back
    
  front:
    build: ./front
    restart: on-failure
    command: ["npm", "start"]
    volumes:
      - ./front:/app/front
      - node-modules:/app/front/node_modules
    ports:
      - "3000:3000"
    container_name: react_front  

volumes:
  node-modules: