# Generated by Django 3.1.5 on 2021-02-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='owner',
            new_name='members',
        ),
    ]
