# Generated by Django 3.1.5 on 2021-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='code',
            field=models.CharField(default=1904057087050664900, max_length=64, unique=True),
        ),
    ]
