# Generated by Django 3.1.5 on 2021-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0002_auto_20210220_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='fakehub_app.Label'),
        ),
    ]
