# Generated by Django 3.1.5 on 2021-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0002_commit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=64, unique=True),
        ),
    ]
