# Generated by Django 3.1.5 on 2021-02-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0003_auto_20210212_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=206605910568426112, max_length=64, unique=True),
        ),
    ]
