# Generated by Django 3.1.5 on 2021-01-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0003_auto_20210126_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='author',
            new_name='owner',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository')),
            ],
        ),
    ]
