# Generated by Django 3.1.5 on 2021-02-14 15:50
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0006_auto_20210212_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='repo_owner', to=settings.AUTH_USER_MODEL, null=True)
        ),
        migrations.AlterField(
            model_name='repository',
            name='collaborators',
            field=('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL, null=True))
        ),
    ]
