# Generated by Django 3.1.5 on 2021-02-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0006_auto_20210212_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='My new awesome page'),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='New page', max_length=100),
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=13974701028262971376, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fakehub_app.wiki'),
        ),
    ]
