# Generated by Django 3.1.5 on 2021-02-03 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0006_auto_20210203_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
