# Generated by Django 3.1.5 on 2021-02-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0008_label_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.AddField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
            preserve_default=False,
        ),
    ]
