# Generated by Django 3.1.5 on 2021-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0008_auto_20210214_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=3041814720698640674, max_length=64, unique=True),
        ),
    ]
