# Generated by Django 3.1.5 on 2021-02-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0010_auto_20210204_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
        ),
    ]
