# Generated by Django 3.1.5 on 2021-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0010_auto_20210214_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=1662450375155342866, max_length=64, unique=True),
        ),
    ]
