# Generated by Django 3.1.5 on 2021-02-04 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0011_auto_20210204_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
            preserve_default=False,
        ),
    ]
