# Generated by Django 3.1.5 on 2021-02-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0009_auto_20210214_2154'),
        ('fakehub_app', '0012_auto_20210214_2239'),
    ]

    operations = [
    ]
