# Generated by Django 3.1.5 on 2021-02-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0005_auto_20210131_2204'),
        ('fakehub_app', '0013_auto_20210204_2358'),
    ]

    operations = [
    ]
