# Generated by Django 3.1.5 on 2021-02-15 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0013_merge_20210215_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=4063015407606743312, max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='column',
            name='task',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.column'),
        ),

        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
