# Generated by Django 3.1.5 on 2021-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0014_auto_20210215_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=4579572725213498828, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
