# Generated by Django 3.1.5 on 2021-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0015_auto_20210215_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=15565942065966238269, max_length=64, unique=True),
        ),
    ]
