# Generated by Django 3.1.5 on 2021-02-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0016_auto_20210216_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='wiki',
        ),
        migrations.AddField(
            model_name='page',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fakehub_app.repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=7337091040822996458, max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='Wiki',
        ),
    ]
