# Generated by Django 3.1.5 on 2021-02-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0017_auto_20210216_1927'),
        ('fakehub_app', '0017_auto_20210216_2349'),
    ]

    operations = [
    ]
