# Generated by Django 3.1.5 on 2021-02-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0018_merge_20210217_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=3866142615483112452, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakehub_app.repository'),
        ),
    ]
