# Generated by Django 3.1.5 on 2021-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0019_auto_20210217_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=9089606722216753331, max_length=64, unique=True),
        ),
    ]
