# Generated by Django 3.1.5 on 2021-02-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0021_auto_20210217_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=10314401179459766938, max_length=64, unique=True),
        ),
    ]
