# Generated by Django 3.1.5 on 2021-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0023_auto_20210218_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=3160419570688569424, max_length=64, unique=True),
        ),
    ]
