# Generated by Django 3.1.5 on 2021-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0024_auto_20210219_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=6251779282654309648, max_length=64, unique=True),
        ),
    ]
