# Generated by Django 3.1.5 on 2021-02-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0024_auto_20210218_2142'),
        ('fakehub_app', '0009_auto_20210214_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=1103916683468549069, max_length=64, unique=True),
        ),
    ]
