# Generated by Django 3.1.5 on 2021-02-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0024_auto_20210219_0040'),
        ('fakehub_app', '0025_auto_20210218_2148'),
    ]

    operations = [
    ]
