# Generated by Django 3.1.5 on 2021-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0025_auto_20210219_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
