# Generated by Django 3.1.5 on 2021-02-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0026_merge_20210219_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=13664044986435769713, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='task_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
