# Generated by Django 3.1.5 on 2021-02-19 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0027_auto_20210219_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
