# Generated by Django 3.1.5 on 2021-02-19 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0027_auto_20210219_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=16777491711528476333, max_length=64, unique=True),
        ),
    ]
