# Generated by Django 3.1.5 on 2021-02-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0028_auto_20210220_0041'),
        ('fakehub_app', '0028_auto_20210219_2101'),
    ]

    operations = [
    ]
