# Generated by Django 3.1.5 on 2021-02-20 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0029_merge_20210220_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='task_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
