# Generated by Django 3.1.5 on 2021-02-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0030_auto_20210220_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to='fakehub_app.user'),
            preserve_default=False,
        ),
    ]
