# Generated by Django 3.1.5 on 2021-02-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakehub_app', '0004_auto_20210212_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.CharField(blank=True, default=7643573139534921990, max_length=64, unique=True),
        ),
    ]
